# Generated by Django 4.2.7 on 2024-01-16 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cat_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.categoria'),
        ),
        migrations.CreateModel(
            name='ProductCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic_name', models.CharField(default=None, max_length=255, verbose_name='Название характеристики')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='website.product')),
            ],
        ),
    ]
