# Generated by Django 4.2.7 on 2024-01-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_product_cat_id_productcharacteristic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(default=None, max_length=100, verbose_name='категория'),
        ),
    ]
