# Generated by Django 4.2.7 on 2024-01-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_categoria_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteris',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Характеристики'),
        ),
        migrations.DeleteModel(
            name='ProductCharacteristic',
        ),
    ]
